### ISSUE TITLE
TypeError: Cannot read property 'locale' of null - when using Nuxt Router & router.push

### ISSUE THREAD

**Issue by simplenotezy** [nuxt-community/nuxt-i18n#601]
### Version

[6.5.0](https://github.com/nuxt-i18n/releases/tag/6.5.0)

### Steps to reproduce

Sometimes I am getting this error, when I am clicking a <nuxt-link>:

	"TypeError: Cannot read property 'locale' of null
	at Object.localePath (webpack-internal:///./.nuxt/nuxt-i18n/plugin.routing.js:52:27)
	at VueComponent.eval (webpack-internal:///./.nuxt/nuxt-i18n/plugin.routing.js:180:27)
	at VueComponent.productClicked (webpack-internal:///./node_modules/babel-loader/lib/index.js?!./node_modules/vue-loader/lib/index.js?!./components/templates/ProductDisplay.vue?vue&type=script&lang=js&:41:32)
	at click (webpack-internal:///./node_modules/vue-loader/lib/loaders/templateLoader.js?!./node_modules/vue-loader/lib/index.js?!./components/templates/ProductDisplay.vue?vue&type=template&id=1ca4bc44&scoped=true&:22:22)
	at invokeWithErrorHandling (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:1853:26)
	at HTMLAnchorElement.invoker (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:2178:14)
	at HTMLAnchorElement.original._wrapper (webpack-internal:///./node_modules/vue/dist/vue.runtime.esm.js:6907:25)"

Specifically, my <nuxt-link> looks like this:

    <nuxt-link :to="localePath({ name: 'product-slug', params: { slug: product.slug } })" :event="''" @click.prevent.native="productClicked($event)" class="product-container column">

And the productClicked looks like this:

		productClicked ($event) {
			this.$emit('productClicked', this.product);

			if (!this.disableLink) {
				this.$router.push(this.localePath({ name: 'product-slug', params: { slug: this.product.slug } })); // this is where the error begins
			}
		}

The error doesn't happen every time.

See attached screenshots.
![vuenuxt-1.png](https://cmty.s3.eu-west-1.amazonaws.com/110467581/b6fea150-5319-11ea-a59c-89d37796919e.png)
![vuenuxt-2.png](https://cmty.s3.eu-west-1.amazonaws.com/110467581/b9bbc580-5319-11ea-a59c-89d37796919e.png)
![vuenuxt-3.png](https://cmty.s3.eu-west-1.amazonaws.com/110467581/bca81000-5319-11ea-a59c-89d37796919e.png)
![vuenuxt-4.png](https://cmty.s3.eu-west-1.amazonaws.com/110467581/bf142e00-5319-11ea-a59c-89d37796919e.png)

### What is expected ?

Link should be fired without errors

### What is actually happening?

Errors are happening

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt-i18n/issues/c400">#c400</a>)</em></sub></div>

**Comment by rchl** [comment]
Your `@click.prevent.native` handler can't and doesn't prevent nuxt-link navigating to another page. Thus, depending on the timing, you are ending up running the handler potentially after the page has been destroyed. You can use plain `a` link instead in this case to fix your problem probably.
