### ISSUE TITLE
how to setup nuxt i18n for multi domains and deploy on multiple domain? 

### ISSUE THREAD

**Issue by vinayakgargote** [nuxt-community/nuxt-i18n#794]
When I set differentDomains: true, it throws an error while generating.

TypeError: Cannot read property 'headers' of undefined
    at getLocaleDomain (.nuxt/nuxt-i18n/utils-common.js:88:0)
    at plugin_main (.nuxt/nuxt-i18n/plugin.main.js:238:0)
    at createApp (.nuxt/index.js:202:0)
    at async module.exports.__webpack_exports__.default (.nuxt/server.js:81:0)

has anyone deployed on multiple domains for eg example.com and example.fr ?

**Comment by rchl** [comment]
It does indeed crash when using `differentDomains` and `nuxt generate` (or `nuxt export`).

The crash issues should be fixed by #796 but I'm not sure how well the feature will work with statically generated pages as apparently nobody really used it so far.
